### ISSUE TITLE
Persistent storage support

### ISSUE THREAD

**Issue by kelvinji2009** [iamazy/audit-spring-cloud-starter#1]
Do you have a plan to support persistent storage?

**Comment by iamazy** [comment]
> Do you have a plan to support persistent storage?

I had provided a interface named [IAuditOutput.java](https://github.com/iamazy/audit-spring-cloud-starter/blob/master/src/main/java/com/iamazy/springcloud/audit/configuration/IAuditOutput.java), if you want to store the log in persitent storage, you can implement [IAuditOutput.java](https://github.com/iamazy/audit-spring-cloud-starter/blob/master/src/main/java/com/iamazy/springcloud/audit/configuration/IAuditOutput.java) and put it in spring bean container

**Comment by kelvinji2009** [comment]
@iamazy Yeap. Thanks a lot.
